name: 'build Android 🤖'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  android-build:

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm, aarch64]
        ffmpeg_version: ["6.1.1", "7.0"]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install meson ninja-build nasm

    - name: Get ffmpeg source code
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-${{ matrix.ffmpeg_version }}.tar.xz
        tar -xf ffmpeg-${{ matrix.ffmpeg_version }}.tar.xz

    - name: Compile ffmpeg source with the ndk toolchain for Android & install it to a specific directory
      run: |
        cd ffmpeg-${{ matrix.ffmpeg_version }}
        android_suffix="android"
        compiler=${{ matrix.arch }}

        if [ ${{ matrix.arch }} == "arm" ]; then
          android_suffix="androideabi"
          compiler="armv7a"
        fi

        NDK_BIN_PATH=/usr/local/lib/android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin
        ./configure \
        --disable-everything --disable-doc --disable-static --disable-autodetect --disable-programs \
        --enable-shared --enable-cross-compile --enable-jni --enable-mediacodec --enable-hwaccels  \
        --enable-avdevice --enable-swresample \
        --arch=${{ matrix.arch }} --target-os=android \
        --cross-prefix=$NDK_BIN_PATH/llvm- \
        --cc=$NDK_BIN_PATH/${compiler}-linux-${android_suffix}28-clang \
        --prefix=$HOME/ffmpeg-install-${{ matrix.arch }}

        make install -j$(($(nproc)+1))

    - name: Build nope.media for Android
      run: |
        PKG_CONFIG_LIBDIR=$HOME/ffmpeg-install-${{ matrix.arch }}/lib/pkgconfig/ \
        meson setup --cross-file .github/meson-android-${{ matrix.arch }}.ini builddir
        meson compile -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: android-logs-${{ matrix.arch }}
        path: builddir/meson-logs
