name: 'tests Linux'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  linux:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_type: [static, shared]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install meson ninja-build
        sudo apt -y install libsdl2-dev libva-dev
        sudo apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev

    - name: Run tests
      run: |
        meson setup --buildtype release builddir -Dvaapi=enabled --default-library ${{ matrix.build_type }}
        meson test -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: linux-${{ matrix.build_type }}-logs
        path: builddir/meson-logs

  valgrind:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install meson ninja-build
        sudo apt -y install libsdl2-dev
        sudo apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
        sudo apt -y install valgrind

    - name: Run memory tests
      run: |
        meson setup --buildtype debugoptimized builddir
        meson test --wrapper "valgrind --error-exitcode=1" -C builddir -v
