name: 'tests Mac'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  macos:

    runs-on: macos-latest

    strategy:
      matrix:
        build_type: [static, shared]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install meson ninja
        brew install sdl2
        brew install ffmpeg
        brew install pkg-config

    - name: Run tests
      run: |
        meson setup --buildtype release builddir --default-library ${{ matrix.build_type }}
        meson test -C builddir -v

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.build_type }}-logs
        path: builddir/meson-logs
