name: 'tests Windows'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  mingw:

    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [static, shared]
        include:
          - player: disabled
            build_type: static
          - player: enabled
            build_type: shared

    defaults:
      run:
        shell: msys2 {0}

    steps:

      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Start a 64 bit Mingw environment
          update: true

      - name: Install dependencies
        run: |
          pacman -S --noconfirm --needed git
          pacman -S --noconfirm --needed mingw-w64-x86_64-{toolchain,ffmpeg}
          pacman -S --noconfirm mingw-w64-x86_64-python3-pip
          pacman -S --noconfirm --needed mingw-w64-x86_64-meson

      - name: Setup
        run: |
          meson setup builddir --default-library ${{ matrix.build_type }} -Dplayer=${{ matrix.player }}

      - name: Build
        run: |
          meson compile -C builddir

      - name: Test
        run: |
          meson test -C builddir

      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: mingw-${{ matrix.build_type }}-logs
          path: builddir/meson-logs


  msvc:

    runs-on: windows-latest
    env:
      FFMPEG_SRC: ffmpeg-n6.0-12-ga6dc92968a-win64-gpl-shared-6.0
      FFMPEG_URL: https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-04-03-12-51

    strategy:
      matrix:
        build_type: [static, shared]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install meson and pkg-config
      shell: bash
      run: |
        pip install meson
        choco install --allow-empty-checksums pkgconfiglite

    - name: Install dependencies
      shell: bash
      run: |
        curl -L -o ${{ env.FFMPEG_SRC }}.zip ${{ env.FFMPEG_URL }}/${{ env.FFMPEG_SRC }}.zip
        unzip ${{ env.FFMPEG_SRC }}.zip
        ln -s ${{ env.FFMPEG_SRC }} ffmpeg

    - name: Setup
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson setup builddir --backend vs --buildtype release --default-library ${{ matrix.build_type }} ^
        --pkg-config-path "D:\a\nope.media\nope.media\ffmpeg\lib\pkgconfig"

    - name: Build
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson compile -C builddir

    - name: Test
      shell: cmd
      run: |
        set PATH=D:\a\nope.media\nope.media\ffmpeg\bin;%PATH%
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64 && ^
        meson test -C builddir

    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: msvc-${{ matrix.build_type }}-logs
        path: builddir/meson-logs
